inject:
  head:
  - ... 
  bottom:
  - <script type="text/javascript" src="https://unpkg.zhimg.com/jquery@latest/dist/jquery.min.js"></script>
  - ...
  - <script data-pjax type="text/javascript" src="/js/{use_js}.js"></script>
  - ...